// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGame;

import ProjectGame.Hero;

/************************************************************/
/**
 * 
 */
public class Cleric extends Hero {

	/**
	 * @param healPower
	 * @param maxHP
	 * @param name
	 */
	public Cleric(int healPower, int maxHP, String name) {
		super(healPower, maxHP, name);
		// TODO Auto-generated constructor stub
			
	}
	public Cleric() {
		super();
		this.name ="Cleric";
	}
	
	@Override
	public void attack(Role hero) {
		hero.hp = hero.hp + this.attackPower;
	}
	
};
