// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGame;

import java.util.ArrayList;
import java.util.Scanner;

import ProjectGame.Hero;
import ProjectGame.Monster;

/************************************************************/
/**
 * 
 */
public class InitTeams {

	/**
	 * 
	 */
	private ArrayList<Monster> teamMonsters=new ArrayList<Monster>();
	/**
	 * 
	 */
	
	private ArrayList<Hero> teamHeros=new ArrayList<Hero>();
	/**
	 * 
	 */
	public InitTeams() {
		super();
		this.teamHeros.add(new Assasin());
		this.teamHeros.add(new Warrior());
		this.teamHeros.add(new Paladin());
		this.teamHeros.add(new Cleric());
	}



	/**
	 * 
	 */
	public ArrayList<Hero> selectHeroes(){
		ArrayList<Hero> choiceHeros=new ArrayList<Hero>();
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
 	   	System.out.println("Who do you choose for your quest into EtherDungeons?");
	 	for (int i=0;i<this.teamHeros.size() ;i++) {
	 		System.out.println((i+1)+this.teamHeros.get(i).getName()+"\t"+this.teamHeros.get(i));
	 	}
 	   	Scanner input = new Scanner(System.in);
 	   	int option;
 	   	do {
 	   		option = input.nextInt();
 	   		choiceHeros.add(this.teamHeros.get(option-1));
 	   	}while(choiceHeros.size()!= 4);
 	   return choiceHeros;
	}
	
	public ArrayList<Monster> randMonsters() {
		this.teamMonsters.clear();
		ArrayList<Monster> choiceMonsters=new ArrayList<Monster>();
		double r; // random number
        r = 6*Math.random()+1; //6 can be modified to a liking of your choice 
        int p =(int) Math.floor(r);
        if (p <= 2) {
        for(int i=0;i<p;i++) { 
        		this.teamMonsters.add(new KingKoopa (99,200,"KingKoopa"));
        	}
        }
        if (p > 2 && p<=5) {
        	for(int i=0;i<2;i++) {
        		this.teamMonsters.add(new Mummy (60,60,"Mummy"));
        		this.teamMonsters.add( new Spider (30,20,"Spydy"));
        	}
        }
        if (p ==6) {
        	for(int i=0;i<2;i++) {
        		this.teamMonsters.add(new Orc (50,100,"Orc"));
        		this.teamMonsters.add(new Ogre (50,150,"Ogre"));
        	}
        	this.teamMonsters.add(new Slime (10,30,"Orc slime"));
        	this.teamMonsters.add( new Spider (30,60,"Ogre Pet Spider"));
        }
        for(int i = 0;i<this.teamMonsters.size();i++) {
        	choiceMonsters.add(this.teamMonsters.get(i));
        }
        return choiceMonsters;
       }



	/**
	 * @return the teamMonsters
	 */
	public ArrayList<Monster> getTeamMonsters() {
		return teamMonsters;
	}



	/**
	 * @return the teamHeros
	 * 
	 */
	public ArrayList<Hero> getTeamHeros() {
		return teamHeros;
	}


	
//	public String toString() {
//		return (this.hp + "/" + this.maxHP );
	
};
