// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGame;

import ProjectGame.Monster;

/************************************************************/
/**
 * 
 */
public class KingKoopa extends Monster {

	/**
	 * @param attackPower
	 * @param maxHP
	 * @param name
	 */
	public KingKoopa(int attackPower, int maxHP, String name) {
		super(attackPower, maxHP, name);
		// TODO Auto-generated constructor stub
	}
	
};
