// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGame;

import ProjectGame.Role;

/************************************************************/
/**
 * 
 */
public class Monster extends Role {

	/**
	 * @param attackPower
	 * @param maxHP
	 * @param name
	 */
	public Monster(int attackPower, int maxHP, String name) {
		super(attackPower, maxHP, name);
		// TODO Auto-generated constructor stub
	}
	public String toString() {
		return (this.hp + "/" + this.maxHP );
	}
	
};
