// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGame;

import ProjectGame.Hero;

/************************************************************/
/**
 * 
 */
public class Paladin extends Hero {

	/**
	 * @param attackPower
	 * @param maxHP
	 * @param name
	 */
	public Paladin(int attackPower, int maxHP, String name) {
		super(attackPower, maxHP, name);
		// TODO Auto-generated constructor stub
	}
	public Paladin() {
		super();
		this.name ="Paladin";
	}
};
