// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGame;

/************************************************************/
/**
 * 
 */
public class Role {
	/**
	 * 
	 */
	protected  int hp;
	/**
	 * 
	 */
	protected int attackPower;
	/**
	 * 
	 */
	protected  int maxHP;
	/**
	 * 
	 */
	protected String name;
	
	public Role() {
		this.attackPower = 30;
		this.maxHP = 100;
		this.name = "Default";
		this.hp= 100;
	}

	public Role(int attackPower, int maxHP1, String name) {
		super();
		this.attackPower = attackPower;
		this.maxHP = maxHP1;
		this.name = name;
		this.hp=maxHP1;
	}

	/**
	 * @return the hp
	 */
	public int getHp() {
		return this.hp;
	}

	/**
	 * @param hp the hp to set
	 */
	public void setHp(int hp1) {
		this.hp = hp1;
	}

	/**
	 * @return the attackPower
	 */
	public int getAttackPower() {
		return attackPower;
	}

	/**
	 * @param attackPower the attackPower to set
	 */
	public void setAttackPower(int attackPower) {
		this.attackPower = attackPower;
	}

	/**
	 * @return the maxHP
	 */
	public int getMaxHP() {
		return maxHP;
	}

	/**
	 * @param maxHP the maxHP to set
	 */
	public void setMaxHP(int maxHP) {
		this.maxHP = maxHP;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 
	 */
	
	public void attack(Role actor) {
		actor.hp = actor.hp - this.attackPower;
		
	}
};
