// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGame;

import ProjectGame.Game;

/************************************************************/
/**
 * 
 */
public class TestGame {
	/**
	 * 
	 */
	static public Game game;
	public static void main(String[]args) {
		game =new Game();
		game.dispData();	
	}
};
