// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGame;

import ProjectGame.Hero;

/************************************************************/
/**
 * 
 */
public class Warrior extends Hero {

	/**
	 * @param attackPower
	 * @param maxHP
	 * @param name
	 */
	public Warrior(int attackPower, int maxHP, String name) {
		super(attackPower, maxHP, name);
		// TODO Auto-generated constructor stub
	}
	public Warrior() {
		super();
		this.name ="Warrior";
	}
	
};
