// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

/************************************************************/
/**
 *Attack Magnet potion which makes the drinker have a greater chance of being attacked(82% chance).
 */
public class AttackMagnet extends Potions {

	/**
	 * 
	 */
	public AttackMagnet() {
		super();
		this.name ="Attack Magnet";
	}
	/**
	 * @param name
	 */
	public AttackMagnet(String name) {
		super(name);
	}
	/**
	 * This is the drink function defined for Attack Magnet potion.
	 * @param drinker The hero who drinks the potion.
	 */
	@Override
	public void drink(Hero drinker) {
		drinker.setAttackChance(0.82);
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Potion makes "+drinker.getName()+" an "+this.name);
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		
	}
	
	
};
