// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

import ProjectGameVer3.Hero;
import ProjectGameVer3.Role;

/************************************************************/
/**
 * 
 */
public class Beserker extends Hero {
	
	/**
	 * Default parameters for a Beserker.
	 */
	public Beserker() {
		super();
		this.name ="Beserker";
		this.attackPower = 50;
		this.maxHP = 45;
		this.hp = this.maxHP;
	}

	/**
	 * Initializes a Beserker with an attack power, name and Max Health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Beserker(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name+=" the Beserker";
	}

	/**
	 * Initializes a Beserker with a name and default parameters.
	 * @param name
	 */
	public Beserker(String name) {
		super(name);
		this.name+=" the Beserker";
		this.attackPower = 50;
		this.maxHP = 45;
		this.hp = this.maxHP;
	}
	@Override	
	/**
	 * Attack redefined to allow Beserker to heal on killing an opponent.
	 * @param opponent 
	 */
	public void attack(Role opponent) {
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		this.checkPoison();
		if(!this.skip) {
			opponent.getAttacked(this);
			if (opponent.hp<=0) {
				this.hp +=5;
				System.out.println(this.name+" activates Beserker heal on killing "+opponent.name);
			}
		}else {
			System.out.println(this.name+" Skips a turn.");
			this.skip=false;
			int startIndex = this.getName().indexOf("(");
			if (startIndex>0) {
				this.goo=false;
				this.setName(this.getName().substring(0,startIndex));
			}
		}
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");	
	}
	
};
