// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

/************************************************************/
/**
 * Boost potion which increases the attack power of the drinker by 5HP.
 */
public class Boost extends Potions {
	
	/**
	 * 
	 */
	public Boost() {
		super();
		this.name="Boost Potion";
	}
	/**
	 * @param name
	 */
	public Boost(String name) {
		super(name);
	}
	/**
	 * This is the drink function defined for Boost potion, which increases the attack power.
	 * @param drinker The hero who drinks the potion.
	 */
	@Override
	public void drink(Hero drinker) {
		drinker.setAttackPower(drinker.getAttackPower()+5);
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		System.out.println(drinker.name+" gets Attack boost of 5HP by the " + this.name);
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		
	}
	
};
