// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;

import ProjectGameVer3.Hero;
import ProjectGameVer3.Monster;

/************************************************************/
/**
 * 
 */
public class Duelist extends Hero {
	
	/**
	 * Default parameters for a Duelist.
	 */
	public Duelist() {
		super();
		this.name ="Duelist";
		this.attackPower = 65;
		this.maxHP = 50;
		this.hp = this.maxHP;
	}

	/**
	 * Initializes a Duelist with an attack power, name and Max Health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Duelist(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name +=" the Duelist";
	}

	/**
	 * Initializes a Duelist with a name and default parameters.
	 * @param name
	 */
	public Duelist(String name) {
		super(name);
		this.name +=" the Duelist";
		this.attackPower = 65;
		this.maxHP = 50;
		this.hp = this.maxHP;
	}

	@Override
	/**
	 * This overrides the function to make sure the duelist has 2 chances,
	 * the reason the code is large is that it ensures all exceptions and also 
	 * takes into account that if Duelist dies trying to attack due to poison 
	 * @param monster 
	 * @param hero 
	 */
	public void attackChoice(ArrayList<Monster> monster, ArrayList<Hero> heros) {
		for (int i=0;i<monster.size() ;i++) {
	    	if(monster.get(i).getHp()<=0) {
	    		monster.remove(i);
	        }
	    }
	    if(monster.size()!= 0) {
			System.out.println("Duelist Mode activated you will get 2 consecutive chances");
			int l=0;
			while(l!=2) {
				if(this.hp > 0) {
					System.out.println("Who does " +this.name +" attack?") ;
			        for (int i=0;i<monster.size() ;i++) {
						System.out.println((i+1)+". "+monster.get(i).getName());
			        }
			        Scanner input = new Scanner(System.in);
			        int option;
					boolean j;
					do {
							j = false;
						try {
							option = input.nextInt();
							attack(monster.get(option-1));
							if(monster.get(option-1).getHp()<=0) {
								monster.remove(option-1);
							}
						}catch(IndexOutOfBoundsException e ) {
				 		  System.out.println("Input a number between 1-"+monster.size());
				 		  j=true;
						}catch(InputMismatchException k) {
							j=true;
							System.out.println("Input a number between 1-"+monster.size());
							input.next();
							}
					}while(j);
					l++;
					if(monster.size()==0){break;}
				}else {
					System.out.println("Duelist faints in super mode due to poison");
					l=2;
				}
			}
			
		 }
	}
};
