// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;


/************************************************************/
/**
 * Health potion which makes the drinker healed by 10 HP (It will not exceed Maximum HP).
 */
public class Health extends Potions {

	/**
	 * 
	 */
	public Health() {
		super();
		this.name = "Health Potion";
	}
	/**
	 * @param name
	 */
	public Health(String name) {
		super(name);
	}
	/**
	 * This is the drink function defined for Health potion.
	 * @param drinker The hero who drinks the potion.
	 */
	@Override
	public void drink(Hero drinker) {
		drinker.setHp(drinker.getHp()+10);
		if (drinker.getHp() > drinker.getMaxHP()) {
			drinker.setHp(drinker.getMaxHP());
		}
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		System.out.println(drinker.name+" gets a health boost from "+this.name);
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		
	}
	
};
