// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

/************************************************************/
/**
 * This class inherits from the java default class Exception.
 */
public class IllegalEntryException extends Exception {
	static final long serialVersionUID = 42L;

	public IllegalEntryException(String msg) {
        super(msg);
    }
};
