// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;


/************************************************************/
/**
 * A class to initialize the teams involved in the game.
 */
public class InitTeams {
	

	/**
	 * This is where all the characters of the game are initialized.
	 * To add a new character here is where one can add a character
	 */
	public InitTeams() {
		this.heros.add(new Assasin("Altair"));
		this.heros.add(new Paladin("Celeres"));
		this.heros.add(new Warrior("Bahubali"));
		this.heros.add(new Cleric("Zia"));
		this.heros.add(new Rogue("Kokki"));
		this.heros.add(new Beserker("Ragnar"));
		this.heros.add(new Duelist("Hattori"));
		this.heros.add(new Defender("Gregor"));
		this.heros.add(new Monk("Mahakasyapa"));
		for(int i = 0; i<3; i++) {
			this.monsters.add(new Spider());
			this.monsters.add(new Orc());
			this.monsters.add(new Slime());
			this.monsters.add(new Mummy());
			this.monsters.add(new Manticore());
			this.monsters.add(new Ogre());
			this.monsters.add(new Manticore("Kitava"));
		}
	}

	/**
	 * 
	 */
	private ArrayList<Hero> heros = new ArrayList<Hero>();
	/**
	 * 
	 */
	private ArrayList<Monster> monsters =new ArrayList<Monster>();

	/**
	 * This function is used to give the user the choice of heros for the game , the function also throws a 
	 * unique exception IlllegalEntryException if the user chooses the same hero.
	 * @exception IllegalEntryException
	 */
	public ArrayList<Hero> selectHeroes() {
		ArrayList<Hero> choiceHeros=new ArrayList<Hero>();
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
	   	System.out.println("Who do you CHOOSE for your quest into EtherDungeons?(any 4 characters)"
	   			+ " \n[Enter the number then give a SPACE for the next or press ENTER after each entry]");
	 	for (int i=0;i<this.heros.size() ;i++) {
	 		System.out.println((i+1)+". "+this.heros.get(i));
	 	}
	   	Scanner input = new Scanner(System.in);
	   	int option;
	   	String p = "Your Team ";
	   	do {
	   		try {
		   		option = input.nextInt();
		   		if(!choiceHeros.contains(this.heros.get(option-1))) {
		   			choiceHeros.add(this.heros.get(option-1));
		   			p += ", "+this.heros.get(option-1).getName();
		   			System.out.println(p);
		   		}else {
		   			throw new IllegalEntryException("Hero Already chosen choose another");
		   		}
		   		
			}catch(InputMismatchException e){
				System.out.println("Input a number between 1-"+this.heros.size());
				input.next();
			}catch(IndexOutOfBoundsException e){
				System.out.println("Input a number between 1-"+this.heros.size());
			}catch(IllegalEntryException e){
				System.out.println("Hero Already chosen choose another");
			}
	   	}while(choiceHeros.size()!= 4);
	   this.heros.clear();
	   return choiceHeros;
	}

	/**
	 * This function is used to generate a random list of monsters containing either 3 to 4.
	 */
	public ArrayList<Monster> randMonster() {
		ArrayList<Monster> teamMonsters=new ArrayList<Monster>();
		int k[]  = {3,4}; //Monster list size variations
		double r; // random number
        r = k.length*Math.random(); 
        int p =(int) Math.floor(r);
        for(int i=0;i<k[p];i++) {
            int p2 = (int) Math.random()*(this.monsters.size());
            teamMonsters.add(this.monsters.get(p2));  
            this.monsters.remove(this.monsters.get(p2));
        }
        return teamMonsters;
	}


};
