// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

import ProjectGameVer3.Hero;

/************************************************************/
/**
 * The monk by default has a dodge chance of 33%.This is the specialty of the monk.
 */
public class Monk extends Hero {

	/**
	 * Default parameters for a Monk.
	 */
	public Monk() {
		super();
		this.name ="Monk";
		this.attackPower = 80;
		this.maxHP = 35;
		this.hp = this.maxHP;
		this.dodgeChance=0.33;
	}

	/**
	 * Initializes a Monk with an attack power, name and Max Health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Monk(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name+=" the Monk";
	}

	/**
	 * Initializes a Monk with a name and default parameters.
	 * @param name
	 */
	public Monk(String name) {
		super(name);
		this.name+=" the Monk";
		this.attackPower = 80;
		this.maxHP = 35;
		this.hp = this.maxHP;
		this.dodgeChance=0.33;
	}
	
};
