// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

/************************************************************/
/**
 * 
 */
public class Mummy extends Monster {
	
	/**
	 * Default parameters for a mummy
	 */
	public Mummy() {
		super();
		this.name ="Mummy";
		this.attackPower = 80;
		this.maxHP = 50;
		this.hp = this.maxHP;
	}

	/**
	 * This initializes a Mummy with name , Attack Power and max health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Mummy(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name += " Mummy";
	}

	/**
	 * This initializes a Mummy with name and default parameters. 
	 * @param name
	 */
	public Mummy(String name) {
		super(name);
		this.name += " Mummy";
		this.attackPower = 80;
		this.maxHP = 50;
		this.hp = this.maxHP;
	}
	@Override

	/**
	 * The redefinition of attack in mummy is due to the fact that the mummy's skip parameter needs to 
	 * change once it attacks unlike other monsters.
	 * @param opponent 
	 */
	public void attack(Role opponent) {
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		this.checkPoison();
		if(!this.skip) {
			opponent.getAttacked(this);
			this.skip =true;
		}else {
			System.out.println(this.name+ " recuperates from its previous attack and doesn't attack");
			this.skip =false;
		}
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
	}
};
