// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;



/************************************************************/
/**
 * The Class defines a monster Ogre who inherits the same characteristics as a monster.
 */
public class Ogre extends Monster {

	/**
	 * Default parameters of Ogre
	 */
	public Ogre() {
		super();
		this.name = "Ogre";
		this.attackPower = 30;
		this.maxHP = 80;
		this.hp = this.maxHP;
	}

	/**
	 * This initializes an Ogre with name, Attack Power and max health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Ogre(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name += " the Ogre";
	}

	/**
	 * This initializes an Ogre with name and default parameters. 
	 * @param name
	 */
	public Ogre(String name) {
		super(name);
		this.name += " the Ogre";
		this.attackPower = 30;
		this.maxHP = 80;
		this.hp = this.maxHP;
	}
	
};
