// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

/************************************************************/
/**
 * 
 */
public class Paladin extends Hero {

	/**
	 * Default parameters for a Paladin.
	 */
	public Paladin() {
		super();
		this.name ="Paladin";
		this.attackPower = 20;
		this.maxHP = 95;
		this.hp = this.maxHP;
	}

	/**
	 * Initializes an Assasin with an attack power, name and Max Health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Paladin(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name += " the Paladin";
	}

	/**
	 * Initializes an Assasin with a name and default parameters.
	 * @param name
	 */
	public Paladin(String name) {
		super(name);
		this.name += " the Paladin";
		this.attackPower = 20;
		this.maxHP = 95;
		this.hp = this.maxHP;
	}
	
};
