// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

import ProjectGameVer3.Hero;

/************************************************************/
/**
 * 
 */
public abstract class Potions {
	
	/**
	 * 
	 */
	public Potions() {
		this.name = "Potion";
	}


	/**
	 * @param name
	 */
	public Potions(String name) {
		this.name = name;
	}
	/**
	 * 
	 */
	protected String name;
	

	/**
	 * 
	 * @param drinker 
	 */
	public abstract void drink(Hero drinker);
};
