// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

import ProjectGameVer3.Hero;
import ProjectGameVer3.Role;

/************************************************************/
/**
 *  
 */
public class Rogue extends Hero {
	
	/**
	 * Default parameters for a Rogue.
	 */
	public Rogue() {
		super();
		this.name ="Rogue";
		this.attackPower = 50;
		this.maxHP = 35;
		this.hp = this.maxHP;
	}

	/**
	 * Initializes a Rogue with an attack power, name and Max Health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Rogue(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name +=" the Rogue";
	}

	/**
	 * Initializes a Rogue with a name and default parameters.
	 * @param name
	 */
	public Rogue(String name) {
		super(name);
		this.name +=" the Rogue";
		this.attackPower = 50;
		this.maxHP = 35;
		this.hp = this.maxHP;
	}

	/**
	 * The specialty of Rogue is that , a Rogue can poison a monster for 3 turns
	 *  i.e set poison to 3 .There are more if statements for better string outputs
	 *  to make the story more precise.
	 * @param opponent 
	 */
	public void attack(Role opponent) {
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		this.checkPoison();
		if(!this.skip) {
			opponent.getAttacked(this);
			if( !opponent.dodge ) {
				if(opponent.poisoned == 0) {
					opponent.poisoned =3;
					System.out.println(this.name+" throws a poisoned dart at "+opponent.name);
					opponent.setName(opponent.name+" (poisoned) ");
				}else {
					opponent.poisoned =3;
					System.out.println(opponent.name+" is poisoned again by a whizzing dart of "+this.name);
				}
			}else {
				System.out.println(this.name+"'s dart misses.");
			}
		}else {
			System.out.println(this.name+" Skips a turn.");
			this.skip=false;
			int startIndex = this.getName().indexOf("(");
			this.setName(this.getName().substring(0,startIndex));
			
		}
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
	}
};
