// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;


/************************************************************/
/**
 * 
 */
public class Slime extends Monster {
	
	/**
	 * Default parameters of Slime.
	 */
	public Slime() {
		super();
		this.name = "Slime";
		this.maxHP = 25;
		this.attackPower = 15;
		this.hp = this.maxHP;
	}

	/**
	 * This initializes a Slime with name , Attack Power and max health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Slime(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name += " Slime";
	}

	/**
	 * @param name
	 */
	public Slime(String name) {
		super(name);
		this.name += " Slime";
		this.maxHP = 25;
		this.attackPower = 15;
		this.hp = this.maxHP;
	}

	/**
	 * This function changes the skip and goo parameter of the victim of Slime. The reason of 
	 * why a goo parameter is needed is that if a Role is in goo he should not be able to retaliate.
	 * @param opponent 
	 */
	public void attack(Role opponent) {
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		this.checkPoison();
		opponent.goo =true;
		opponent.getAttacked(this);
		if(!opponent.dodge) {
			if (!opponent.skip) {
				opponent.skip =true;;
				opponent.setName(opponent.name+"(in goo)");
				System.out.println(opponent.name+" will skip a turn, to recover from goo");
			}else {
				System.out.println(this.name+" engulfs "+opponent.name+" again in goo.");
			}
		}else {
			opponent.goo=false;
		}
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
	}
};
