// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

/************************************************************/
/**
 * 
 */
public class Spider extends Monster {
	
	/**
	 *  Default parameters of Spider.
	 */
	public Spider() {
		super();
		this.name = "Spider";
		this.maxHP = 35;
		this.attackPower = 20;
		this.hp = this.maxHP;
	}

	/**
	 *  This initializes an Spider with name , Attack Power and max health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Spider(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name += " the Spider";
	}

	/**
	 * This initializes an Spider with name and default parameters. 
	 * @param name
	 */
	public Spider(String name) {
		super(name);
		this.name += " Spider";
		this.maxHP = 35;
		this.attackPower = 20;
		this.hp = this.maxHP;
	}

	/**
	 * The attack of the spider is redefined as the spider can either attack or poison (a 50% chance of each)
	 * When attacked an opponent can retaliate but when poisoned by Spider they can't.
	 * @param opponent 
	 */
	@Override
	public void attack(Role opponent) {
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
		this.checkPoison();
		double r; // random number
        r = Math.random(); 
		if(r <= 0.5) {
			opponent.getAttacked(this);
		}else{
			if(opponent.poisoned == 0) {
				opponent.poisoned =3;
				opponent.setName(opponent.name+"(poisoned)");
				System.out.println(this.name+" gives a venomous bite to "+opponent.name);
			}else {
				opponent.poisoned =3;
				System.out.println(this.name+" once again gives a venomous bite to "+opponent.name);
			}
			//opponent.getAttacked(this) , the opponent can retaliate if this is added but its removed to make the game interesting
		}
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
	}
};
