// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;

import ProjectGameVer3.Game;

/************************************************************/
/**
 * This is the class used to run the program.
 */
public class TestGame {
	/**
	 * 
	 */
	static public Game game;
	public static void main(String[]args) {
		game =new Game();
		game.run();	
	}
};
