// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ProjectGameVer3;


/************************************************************/
/**
 * 
 */
public class Warrior extends Hero {

	/**
	 * Default parameters for a Warrior.
	 */
	public Warrior() {
		super();
		this.name ="Warrior";
		this.attackPower = 50;
		this.maxHP = 80;
		this.hp = this.maxHP;
	}

	/**
	 * Initializes a Warrior with an attack power, name and Max Health points.
	 * @param attackPower
	 * @param name
	 * @param maxHP
	 */
	public Warrior(int attackPower, String name, int maxHP) {
		super(attackPower, name, maxHP);
		this.name +=" the Warrior";
	}

	/**
	 * Initializes a Warrior with a name and default parameters.
	 * @param name
	 */
	public Warrior(String name) {
		super(name);
		this.name +=" the Warrior";
		this.attackPower = 50;
		this.maxHP = 80;
		this.hp = this.maxHP;
	}
	
};
